# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    container_name: 'recipe-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=recipes'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=spring'
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'